### ISSUE TITLE
can not run cargo leptos watch

### ISSUE THREAD

**Issue by dlintw** [leptos-rs/start-axum#5]
I just install the rustup and stable rust 1.83.0. And follow this README to do till `cd hello-ssr`. All works.

When I type 'cargo leptos watch', it can not compile.  I found the solution is `rustup target add wasm32-unknown-unknown` .  It is recommend install it automatically in the install process of leptos, or said before the `## Running your project` section.

**Comment by gbj** [comment]
This is described in the README already https://github.com/leptos-rs/start-axum?tab=readme-ov-file#installing-additional-tools

**Comment by dlintw** [comment]
I think, it should describe before this command, for a novice user like me, it make me confuse.
